services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container-testnet
    networks:
      - mynetworktestnet
    depends_on:
      - indexer

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    container_name: indexer-container-testnet
    networks:
      - mynetworktestnet
    volumes:
      - ./indexer/data:/app/data

  explorer:
    build:
      context: ./explorer
      dockerfile: Dockerfile
    env_file: 
      - ./explorer/.env
    ports:
      - "${TESTNET_EXPLORER_PORT}:${TESTNET_EXPLORER_PORT}"
    container_name: explorer-container-testnet
    depends_on:
      - api
    networks:
      - mynetworktestnet
    command: ["npm", "run", "docker-start-testnet"]

networks:
  mynetworktestnet:
    driver: bridge
