services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "${API_PORT}:${API_PORT}"
    container_name: api-container
    networks:
      - mynetwork
    # depends_on:
    #   - mongodb

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    env_file:
      - ./indexer/.env
    ports:
      - "${INDEXER_PORT}:${INDEXER_PORT}"
    container_name: indexer-container
    # depends_on:
    #   - mongodb
    networks:
      - mynetwork

  explorer:
    build:
      context: ./explorer
      dockerfile: Dockerfile
    env_file:
      - ./explorer/.env
    ports:
      - "${EXPLORER_PORT}:${EXPLORER_PORT}"
    container_name: explorer-container
    # depends_on:
    #   - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
